In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\lohit\OneDrive\Documents\assessement-date.csv', low_memory=False)
df

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
0,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
2,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
3,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
4,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182236,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
182237,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
182238,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
182239,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
182240,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [2]:
df.shape

(182241, 76)

In [3]:
type(df.loc['CM_ID':'GROSS_AREA'])

pandas.DataFrame

In [4]:
a=df.columns
for i,a in enumerate(a):
    print(i,a)

0 CM_ID
1 BLDG_SEQ
2 geocode_latitude
3 STRUCTURE_CLASS
4 BED_RMS
5 OWNER
6 EXT_FNISHED
7 GROSS_AREA
8 YR_REMODEL
9 HEAT_TYPE
10 FULL_BTH
11 ROOF_STRUCTURE
12 CD_FLOOR
13 GIS_ID
14 MAIL_STATE
15 KITCHEN_STYLE2
16 SFYI_VALUE
17 BTHRM_STYLE3
18 INT_COND
19 KITCHEN_STYLE3
20 LIVING_AREA
21 CITY
22 LU
23 INT_WALL
24 LUC
25 KITCHEN_TYPE
26 OVERALL_COND
27 LAND_VALUE
28 RES_FLOOR
29 BDRM_COND
30 ROOF_COVER
31 PID
32 KITCHEN_STYLE1
33 CORNER_UNIT
34 KITCHENS
35 HLF_BTH
36 FIREPLACES
37 RC_UNITS
38 BLDG_TYPE
39 ZIP_CODE
40 LAND_SF
41 PROP_VIEW
42 Full_Address
43 geocode_location_type
44 NUM_BLDGS
45 MAIL_ADDRESSEE
46 MAIL_CITY
47 YR_BUILT
48 MAIL_ZIP_CODE
49 LU_DESC
50 parcel
51 COM_UNITS
52 ST_NUM
53 HEAT_SYSTEM
54 BTHRM_STYLE1
55 confidence_score
56 TT_RMS
57 OWN_OCC
58 MAIL_STREET_ADDRESS
59 upi
60 EXT_COND
61 UNIT_NUM
62 TOTAL_VALUE
63 ORIENTATION
64 geocode_longitude
65 NUM_PARKING
66 AC_TYPE
67 ST_NAME
68 RES_UNITS
69 geoid
70 GROSS_TAX
71 BTHRM_STYLE2
72 BLDG_VALUE
73 placekey
74 address_placekey
75 building_placekey

In [5]:
df.iloc[0:4,0:5]

          CM_ID  BLDG_SEQ  geocode_latitude  STRUCTURE_CLASS  BED_RMS
0           NaN         1         42.313316  C - Brick/Concr      NaN
1  1.503129e+09         1         42.310857              NaN      4.0
2  1.600175e+09         1         42.299791              NaN      2.0
3  1.600921e+09         1         42.295714              NaN      NaN

In [6]:
df.iloc[[0,1,2,3],[0,2,3,4]]

          CM_ID  geocode_latitude  STRUCTURE_CLASS  BED_RMS
0           NaN         42.313316  C - Brick/Concr      NaN
1  1.503129e+09         42.310857              NaN      4.0
2  1.600175e+09         42.299791              NaN      2.0
3  1.600921e+09         42.295714              NaN      NaN

In [7]:
df.loc[[0,1,2,3,4,5],['NUM_BLDGS','AC_TYPE']]

   NUM_BLDGS         AC_TYPE
0          1             NaN
1          1        N - None
2          1  C - Central AC
3          1        N - None
4          1        N - None
5          1        N - None

In [8]:
df.loc[90:101,'GROSS_AREA':'upi']

,GROSS_AREA,YR_REMODEL,HEAT_TYPE,FULL_BTH,ROOF_STRUCTURE,CD_FLOOR,GIS_ID,MAIL_STATE,KITCHEN_STYLE2,SFYI_VALUE,...,parcel,COM_UNITS,ST_NUM,HEAT_SYSTEM,BTHRM_STYLE1,confidence_score,TT_RMS,OWN_OCC,MAIL_STREET_ADDRESS,upi
90,4915.0,2012.0,W - Ht Water/Steam,3.0,H - Hip,NaN,1603284000,MA,S - Semi-Modern,0,...,1603284000,NaN,8.0,NaN,S - Semi-Modern,HIGH,12.0,Y,8 FOSSDALE RD,urn:reso:upi:2.0:US:25025:1603284000
91,NaN,NaN,NaN,0.0,NaN,NaN,1002546000,MA,NaN,0,...,NaN,NaN,11.0,NaN,NaN,HIGH,NaN,N,11 WYMAN ST #3A,NaN
92,NaN,NaN,NaN,0.0,NaN,NaN,1100851000,MA,NaN,0,...,NaN,NaN,303.0,NaN,NaN,HIGH,NaN,N,301 HIGHLAND ST #2,NaN
93,1404.0,2021.0,F - Forced Hot Air,1.0,G - Gable,0.0,1502459000,MA,NaN,0,...,NaN,NaN,68.0,I - Indiv. Cntrl,M - Modern,HIGH,6.0,N,"68 BIRD ST, Unit 5",NaN
94,NaN,NaN,NaN,0.0,NaN,NaN,1502808000,MA,NaN,0,...,NaN,NaN,NaN,NaN,NaN,LOW,NaN,N,HOWE TE,NaN
95,6033.0,NaN,F - Forced Hot Air,3.0,F - Flat,NaN,1502816000,MA,N - No Remodeling,0,...,NaN,NaN,18.0,NaN,N - No Remodeling,HIGH,18.0,Y,18 HOWE ST,NaN
96,24043.0,2016.0,NaN,0.0,NaN,NaN,1503125000,MA,NaN,0,...,NaN,NaN,21.0,NaN,NaN,HIGH,NaN,N,150 MT VERNON ST STE 520,NaN
97,816.0,NaN,NaN,0.0,NaN,NaN,1503160000,MA,NaN,0,...,1503160000,NaN,1144.0,NaN,NaN,HIGH,NaN,N,1146 DORCHESTER AV &,urn:reso:upi:2.0:US:25025:1503160000
98,4116.0,1999.0,W - Ht Water/Steam,2.0,H - Hip,NaN,1600195000,MA,S - Semi-Modern,0,...,1600195000,NaN,19.0,NaN,S - Semi-Modern,HIGH,11.0,N,15 EVERDEAN ST,urn:reso:upi:2.0:US:25025:1600195000
99,12834.0,2019.0,NaN,0.0,NaN,NaN,1600636000,MA,NaN,0,...,1600636000,NaN,1510.0,NaN,NaN,HIGH,NaN,N,14 MILES DR,urn:reso:upi:2.0:US:25025:1600636000
100,3459.0,NaN,W - Ht Water/Steam,1.0,G - Gable,NaN,1600726000,MA,NaN,0,...,1600726000,NaN,30.0,NaN,S - Semi-Modern,HIGH,8.0,Y,30 PARKMAN ST,urn:reso:upi:2.0:US:25025:1600726000
101,5377.0,1997.0,W - Ht Water/Steam,3.0,F - Flat,NaN,1601152000,MA,S - Semi-Modern,0,...,NaN,NaN,20.0,NaN,S - Semi-Modern,HIGH,12.0,N,20 KING ST #2,NaN

In [9]:
df['FULL_BTH'].value_counts()

FULL_BTH
1.0     64877
2.0     45213
0.0     36939
3.0     19794
4.0      2551
6.0       580
5.0       519
7.0        65
8.0        35
9.0        12
13.0        3
10.0        2
12.0        2
15.0        2
14.0        1
17.0        1
21.0        1
Name: count, dtype: int64

In [10]:
df.loc[(df['ROOF_STRUCTURE']=='H - Hip' )&(df['GIS_ID']==1603284000)]

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
90,NaN,1,42.285332,NaN,6.0,DONOVAN EDWARD R,M - Vinyl,4915.0,2012.0,W - Ht Water/Steam,...,C - Central AC,FOSSDALE RD,NaN,25025.0,"$11,956.21",S - Semi-Modern,"760,900",22k@62j-sjh-tqf,22k@62j-sjh-tqf,22k@62j-sjh-tqf

In [11]:
df.loc[df['GIS_ID']==1603284000,'OWNER':]

,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,FULL_BTH,ROOF_STRUCTURE,CD_FLOOR,GIS_ID,MAIL_STATE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
90,DONOVAN EDWARD R,M - Vinyl,4915.0,2012.0,W - Ht Water/Steam,3.0,H - Hip,NaN,1603284000,MA,...,C - Central AC,FOSSDALE RD,NaN,25025.0,"$11,956.21",S - Semi-Modern,"760,900",22k@62j-sjh-tqf,22k@62j-sjh-tqf,22k@62j-sjh-tqf

In [12]:
df.loc[df['GIS_ID']==1603284000,'OWNER':'GROSS_TAX']

,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,FULL_BTH,ROOF_STRUCTURE,CD_FLOOR,GIS_ID,MAIL_STATE,...,UNIT_NUM,TOTAL_VALUE,ORIENTATION,geocode_longitude,NUM_PARKING,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX
90,DONOVAN EDWARD R,M - Vinyl,4915.0,2012.0,W - Ht Water/Steam,3.0,H - Hip,NaN,1603284000,MA,...,NaN,"1,096,900",NaN,-71.059864,4.0,C - Central AC,FOSSDALE RD,NaN,25025.0,"$11,956.21"

In [13]:
df.loc[df['GIS_ID']==1603284000,['OWNER','GROSS_TAX']]

               OWNER   GROSS_TAX
90  DONOVAN EDWARD R  $11,956.21

In [14]:
df.head(5)

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
0,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
2,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
3,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
4,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk

In [15]:
df.tail(5)

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
182236,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
182237,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
182238,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
182239,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
182240,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [16]:
df.loc[(df['OWNER']=='KPRO RE LLC')&(df['ST_NAME']=='STRATHMORE RD')]

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
182236,2.102313e+09,1,42.33898,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv