In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\lohit\OneDrive\Documents\assessement-date.csv',low_memory=False)
df

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
0,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
2,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
3,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
4,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182236,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
182237,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
182238,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
182239,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
182240,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [2]:
for i,a in enumerate(df.columns):
      print(i,a)

0 CM_ID
1 BLDG_SEQ
2 geocode_latitude
3 STRUCTURE_CLASS
4 BED_RMS
5 OWNER
6 EXT_FNISHED
7 GROSS_AREA
8 YR_REMODEL
9 HEAT_TYPE
10 FULL_BTH
11 ROOF_STRUCTURE
12 CD_FLOOR
13 GIS_ID
14 MAIL_STATE
15 KITCHEN_STYLE2
16 SFYI_VALUE
17 BTHRM_STYLE3
18 INT_COND
19 KITCHEN_STYLE3
20 LIVING_AREA
21 CITY
22 LU
23 INT_WALL
24 LUC
25 KITCHEN_TYPE
26 OVERALL_COND
27 LAND_VALUE
28 RES_FLOOR
29 BDRM_COND
30 ROOF_COVER
31 PID
32 KITCHEN_STYLE1
33 CORNER_UNIT
34 KITCHENS
35 HLF_BTH
36 FIREPLACES
37 RC_UNITS
38 BLDG_TYPE
39 ZIP_CODE
40 LAND_SF
41 PROP_VIEW
42 Full_Address
43 geocode_location_type
44 NUM_BLDGS
45 MAIL_ADDRESSEE
46 MAIL_CITY
47 YR_BUILT
48 MAIL_ZIP_CODE
49 LU_DESC
50 parcel
51 COM_UNITS
52 ST_NUM
53 HEAT_SYSTEM
54 BTHRM_STYLE1
55 confidence_score
56 TT_RMS
57 OWN_OCC
58 MAIL_STREET_ADDRESS
59 upi
60 EXT_COND
61 UNIT_NUM
62 TOTAL_VALUE
63 ORIENTATION
64 geocode_longitude
65 NUM_PARKING
66 AC_TYPE
67 ST_NAME
68 RES_UNITS
69 geoid
70 GROSS_TAX
71 BTHRM_STYLE2
72 BLDG_VALUE
73 placekey
74 address_placekey
75 building_placekey

In [3]:
df.set_index('CITY',inplace=True)

In [4]:
df

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
CITY,,,,,,,,,,,,,,,,,,,,,
DORCHESTER,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
DORCHESTER,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
DORCHESTER,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
DORCHESTER,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
DORCHESTER,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BRIGHTON,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
BRIGHTON,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
BRIGHTON,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
ALLSTON,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
BRIGHTON,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [5]:
df.loc['DORCHESTER',['CM_ID','BED_RMS']]

                   CM_ID  BED_RMS
CITY
DORCHESTER           NaN      NaN
DORCHESTER  1.503129e+09      4.0
DORCHESTER  1.600175e+09      2.0
DORCHESTER  1.600921e+09      NaN
DORCHESTER           NaN      9.0
...                  ...      ...
DORCHESTER           NaN      5.0
DORCHESTER           NaN      6.0
DORCHESTER  1.704091e+09      2.0
DORCHESTER  1.704192e+09      2.0
DORCHESTER           NaN      4.0

[29328 rows x 2 columns]

In [6]:
#or
import pandas as pd
df=pd.read_csv(r'C:\Users\lohit\OneDrive\Documents\assessement-date.csv',low_memory=False,index_col='GIS_ID')
df

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
GIS_ID,,,,,,,,,,,,,,,,,,,,,
1502686000,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1503129000,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
1600175000,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
1600921000,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
1601027000,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102313000,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
2102732000,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
2102770000,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
2200081000,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
2200801000,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [7]:
df.loc[1502686000]

CM_ID                            NaN
BLDG_SEQ                           1
geocode_latitude           42.313316
STRUCTURE_CLASS      C - Brick/Concr
BED_RMS                          NaN
                          ...
BTHRM_STYLE2                     NaN
BLDG_VALUE                   145,300
placekey             23q@62j-sjc-hdv
address_placekey     23q@62j-sjc-hdv
building_placekey    23q@62j-sjc-hdv
Name: 1502686000, Length: 75, dtype: object

In [8]:
df.sort_index()

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
GIS_ID,,,,,,,,,,,,,,,,,,,,,
100001000,NaN,1,42.379204,NaN,6.0,PASCUCCI CARLO,A - Asbestos,3353.0,NaN,W - Ht Water/Steam,...,N - None,PUTNAM ST,NaN,NaN,"$8,632.80",S - Semi-Modern,"594,400",0wu7gqfa4d@62j-sj7-st9,0wu7gqfa4d@62j-sj7-st9,0wu7gqfa4d@62j-sj7-st9
100002000,NaN,1,42.379421,NaN,3.0,SEMBRANO RODERICK,M - Vinyl,3047.0,2000.0,F - Forced Hot Air,...,C - Central AC,Lexington ST,NaN,NaN,"$8,918.38",M - Modern,"619,700",22x@62j-sj7-sdv,22x@62j-sj7-sdv,22x@62j-sj7-sdv
100003000,NaN,1,42.379445,NaN,5.0,GUERRA CHEVARRIA ANA S,M - Vinyl,3392.0,1985.0,S - Space Heat,...,N - None,Lexington ST,NaN,NaN,"$8,767.96",M - Modern,"605,300",22m@62j-sj7-sdv,22m@62j-sj7-sdv,22m@62j-sj7-sdv
100004000,NaN,1,42.379471,NaN,5.0,JB REALTY TRUST,M - Vinyl,3108.0,1991.0,W - Ht Water/Steam,...,N - None,Lexington ST,NaN,NaN,"$8,014.77",S - Semi-Modern,"535,600",22m@62j-sj7-st9,22m@62j-sj7-st9,22m@62j-sj7-st9
100005000,NaN,1,42.379438,NaN,6.0,MARKS TRAVIS JOSEPH,M - Vinyl,3700.0,1978.0,W - Ht Water/Steam,...,N - None,Lexington ST,NaN,25025.0,"$7,974.44",N - No Remodeling,"501,400",232@62j-sj7-st9,232@62j-sj7-st9,232@62j-sj7-st9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2205666000,NaN,1,42.349688,NaN,NaN,CITY OF BOSTON BY FCL,NaN,NaN,NaN,NaN,...,NaN,KNOWLES ST,NaN,NaN,$-,NaN,0,0v5meap5nt@62j-sgj-rkz,0v5meap5nt@62j-sgj-rkz,0v5meap5nt@62j-sgj-rkz
2205667000,NaN,1,42.349688,NaN,NaN,GREALISH MARTIN J TS,NaN,NaN,NaN,NaN,...,NaN,Lake ST,NaN,NaN,$793.52,NaN,0,0mz4e2b7ql@62j-sgj-rkz,0mz4e2b7ql@62j-sgj-rkz,0mz4e2b7ql@62j-sgj-rkz
2205668000,NaN,1,42.340535,NaN,6.0,EAGLE PROPERTY HOLDINGS LLC,M - Vinyl,4291.0,1990.0,W - Ht Water/Steam,...,N - None,Lake ST,NaN,25025.0,"$14,332.41",M - Modern,"850,500",224@62j-shb-z9f,224@62j-shb-z9f,224@62j-shb-z9f
2205669000,NaN,1,42.340302,C - Brick/Concr,NaN,GREALISH MARTIN J TRST,01 - Brick,14520.0,2016.0,NaN,...,NaN,COMMONWEALTH AV,NaN,25025.0,"$62,143.98",NaN,"1,458,800",22j@62j-shb-z9f,22j@62j-shb-z9f,22j@62j-shb-z9f
2205670000,NaN,1,42.340767,C - Brick/Concr,NaN,COMMWLTH OF MASS,03 - Poured Concr,7386.0,NaN,NaN,...,NaN,COMMONWEALTH AV,NaN,25025.0,$-,NaN,"1,342,900",228@62j-shb-z9f,228@62j-shb-z9f,228@62j-shb-z9f

In [9]:
df.sort_index(ascending=False)

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
GIS_ID,,,,,,,,,,,,,,,,,,,,,
2205670000,NaN,1,42.340767,C - Brick/Concr,NaN,COMMWLTH OF MASS,03 - Poured Concr,7386.0,NaN,NaN,...,NaN,COMMONWEALTH AV,NaN,25025.0,$-,NaN,"1,342,900",228@62j-shb-z9f,228@62j-shb-z9f,228@62j-shb-z9f
2205669000,NaN,1,42.340302,C - Brick/Concr,NaN,GREALISH MARTIN J TRST,01 - Brick,14520.0,2016.0,NaN,...,NaN,COMMONWEALTH AV,NaN,25025.0,"$62,143.98",NaN,"1,458,800",22j@62j-shb-z9f,22j@62j-shb-z9f,22j@62j-shb-z9f
2205668000,NaN,1,42.340535,NaN,6.0,EAGLE PROPERTY HOLDINGS LLC,M - Vinyl,4291.0,1990.0,W - Ht Water/Steam,...,N - None,Lake ST,NaN,25025.0,"$14,332.41",M - Modern,"850,500",224@62j-shb-z9f,224@62j-shb-z9f,224@62j-shb-z9f
2205667000,NaN,1,42.349688,NaN,NaN,GREALISH MARTIN J TS,NaN,NaN,NaN,NaN,...,NaN,Lake ST,NaN,NaN,$793.52,NaN,0,0mz4e2b7ql@62j-sgj-rkz,0mz4e2b7ql@62j-sgj-rkz,0mz4e2b7ql@62j-sgj-rkz
2205666000,NaN,1,42.349688,NaN,NaN,CITY OF BOSTON BY FCL,NaN,NaN,NaN,NaN,...,NaN,KNOWLES ST,NaN,NaN,$-,NaN,0,0v5meap5nt@62j-sgj-rkz,0v5meap5nt@62j-sgj-rkz,0v5meap5nt@62j-sgj-rkz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100005000,NaN,1,42.379438,NaN,6.0,MARKS TRAVIS JOSEPH,M - Vinyl,3700.0,1978.0,W - Ht Water/Steam,...,N - None,Lexington ST,NaN,25025.0,"$7,974.44",N - No Remodeling,"501,400",232@62j-sj7-st9,232@62j-sj7-st9,232@62j-sj7-st9
100004000,NaN,1,42.379471,NaN,5.0,JB REALTY TRUST,M - Vinyl,3108.0,1991.0,W - Ht Water/Steam,...,N - None,Lexington ST,NaN,NaN,"$8,014.77",S - Semi-Modern,"535,600",22m@62j-sj7-st9,22m@62j-sj7-st9,22m@62j-sj7-st9
100003000,NaN,1,42.379445,NaN,5.0,GUERRA CHEVARRIA ANA S,M - Vinyl,3392.0,1985.0,S - Space Heat,...,N - None,Lexington ST,NaN,NaN,"$8,767.96",M - Modern,"605,300",22m@62j-sj7-sdv,22m@62j-sj7-sdv,22m@62j-sj7-sdv
100002000,NaN,1,42.379421,NaN,3.0,SEMBRANO RODERICK,M - Vinyl,3047.0,2000.0,F - Forced Hot Air,...,C - Central AC,Lexington ST,NaN,NaN,"$8,918.38",M - Modern,"619,700",22x@62j-sj7-sdv,22x@62j-sj7-sdv,22x@62j-sj7-sdv
100001000,NaN,1,42.379204,NaN,6.0,PASCUCCI CARLO,A - Asbestos,3353.0,NaN,W - Ht Water/Steam,...,N - None,PUTNAM ST,NaN,NaN,"$8,632.80",S - Semi-Modern,"594,400",0wu7gqfa4d@62j-sj7-st9,0wu7gqfa4d@62j-sj7-st9,0wu7gqfa4d@62j-sj7-st9

In [10]:
df.reset_index()

,GIS_ID,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
0,1502686000,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1,1503129000,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
2,1600175000,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
3,1600921000,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
4,1601027000,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182236,2102313000,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
182237,2102732000,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
182238,2102770000,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
182239,2200081000,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
182240,2200801000,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [11]:
df.loc[(df.index==2200081000)&(df['EXT_FNISHED']=='U - Alum Siding')]

,CM_ID,BLDG_SEQ,geocode_latitude,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA,YR_REMODEL,HEAT_TYPE,...,AC_TYPE,ST_NAME,RES_UNITS,geoid,GROSS_TAX,BTHRM_STYLE2,BLDG_VALUE,placekey,address_placekey,building_placekey
GIS_ID,,,,,,,,,,,,,,,,,,,,,
2200081000,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z

In [12]:
df['OWNER'].dtype

In [13]:
a=['KPRO RE LLC','YEE XIAO WEI SITU','TORAH ACADEMY INC']
filt=df['OWNER'].isin(a)
df.loc[filt,['OWNER','geocode_latitude','BED_RMS']]

                        OWNER  geocode_latitude  BED_RMS
GIS_ID
2102787000  TORAH ACADEMY INC         42.345211      5.0
2102613000  TORAH ACADEMY INC         42.341865      4.0
2102787000  TORAH ACADEMY INC         42.345211      2.0
401446000         KPRO RE LLC         42.344639      0.0
504165000         KPRO RE LLC         42.347130      0.0
2102476000        KPRO RE LLC         42.339351      1.0
2102770000  TORAH ACADEMY INC         42.344492      5.0
2204405000  TORAH ACADEMY INC         42.351703      5.0
2102313000        KPRO RE LLC         42.338980      1.0
2102732000  YEE XIAO WEI SITU         42.343485      2.0
2102770000  TORAH ACADEMY INC         42.344492      2.0

In [14]:
df['STRUCTURE_CLASS'].dtype

In [15]:
filt=df['STRUCTURE_CLASS'].str.contains('C - Brick/Concr',na=False)
df.loc[filt,'STRUCTURE_CLASS':'GROSS_AREA']

,STRUCTURE_CLASS,BED_RMS,OWNER,EXT_FNISHED,GROSS_AREA
GIS_ID,,,,,
1502686000,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0
1503076000,C - Brick/Concr,NaN,DANUTA PRUCHNIEWSKI,03 - Poured Concr,8280.0
1502345000,C - Brick/Concr,NaN,MARIO SUSI & SON INC,12 - Conc Block,4080.0
1600599000,C - Brick/Concr,NaN,DORCHESTER-LINCOLN PROPERTES LLC,01 - Brick,14973.0
1601515020,C - Brick/Concr,NaN,DO REAL ESTATE LLC MASS LLC,01 - Brick,5026.0
...,...,...,...,...,...
1800044000,C - Brick/Concr,NaN,DORCHESTER NAZARENE,01 - Brick,6115.0
2201327000,C - Brick/Concr,NaN,CHURCH OF SCIENTOLOGY OF BOSTON INC,01 - Brick,3840.0
2200678010,C - Brick/Concr,NaN,70 LEO OWNER LLC,01 - Brick,NaN
2102168001,C - Brick/Concr,NaN,KRE-BSL HUSKY CHESTNUT PARK LLC,01 - Brick,105000.0
2102495000,C - Brick/Concr,NaN,5520 - 286 & 288 CHESTNUT,01 - Brick,17815.0

In [16]:
df.columns=df.columns.str.replace('_','--')
df

,CM--ID,BLDG--SEQ,geocode--latitude,STRUCTURE--CLASS,BED--RMS,OWNER,EXT--FNISHED,GROSS--AREA,YR--REMODEL,HEAT--TYPE,...,AC--TYPE,ST--NAME,RES--UNITS,geoid,GROSS--TAX,BTHRM--STYLE2,BLDG--VALUE,placekey,address--placekey,building--placekey
GIS_ID,,,,,,,,,,,,,,,,,,,,,
1502686000,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1503129000,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
1600175000,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
1600921000,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
1601027000,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102313000,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
2102732000,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
2102770000,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
2200081000,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
2200801000,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [17]:
df.columns=[x.title() for x in df.columns]
df

,Cm--Id,Bldg--Seq,Geocode--Latitude,Structure--Class,Bed--Rms,Owner,Ext--Fnished,Gross--Area,Yr--Remodel,Heat--Type,...,Ac--Type,St--Name,Res--Units,Geoid,Gross--Tax,Bthrm--Style2,Bldg--Value,Placekey,Address--Placekey,Building--Placekey
GIS_ID,,,,,,,,,,,,,,,,,,,,,
1502686000,NaN,1,42.313316,C - Brick/Concr,NaN,OVALLES PABLO,01 - Brick,2450.0,1988.0,NaN,...,NaN,Hancock ST,NaN,25025.0,"$4,947.87",NaN,"145,300",23q@62j-sjc-hdv,23q@62j-sjc-hdv,23q@62j-sjc-hdv
1503129000,1.503129e+09,1,42.310857,NaN,4.0,MAXWELL REALTY COMPANY LLC A MASS LLC,M - Vinyl,1115.0,2005.0,W - Ht Water/Steam,...,N - None,Bay ST,NaN,NaN,"$5,985.19",NaN,"549,100",22c@62j-sjc-qfz,22c@62j-sjc-qfz,22c@62j-sjc-qfz
1600175000,1.600175e+09,1,42.299791,NaN,2.0,BISCOE DANIEL,C - Cement Board,1499.0,NaN,F - Forced Hot Air,...,C - Central AC,ASHLAND ST,NaN,25025.0,"$8,062.73",M - Modern,"739,700",22b@62j-sjf-35z,22b@62j-sjf-35z,22b@62j-sjf-35z
1600921000,1.600921e+09,1,42.295714,NaN,NaN,48 DIX STYREET CONDOMINIUM TRUST,F - Frame/Clapbrd,NaN,NaN,F - Forced Hot Air,...,N - None,DIX ST,3.0,NaN,$-,NaN,0,22m@62j-sjj-c5z,22m@62j-sjj-c5z,22m@62j-sjj-c5z
1601027000,NaN,1,42.295226,NaN,9.0,398 CENTRE STREET DEVELOPMENT LLC,W - Wood Shake,6036.0,2000.0,W - Ht Water/Steam,...,N - None,CENTRE ST,NaN,NaN,"$10,131.55",M - Modern,"719,300",22k@62j-sjj-mrk,22k@62j-sjj-mrk,22k@62j-sjj-mrk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2102313000,2.102313e+09,1,42.338980,NaN,1.0,KPRO RE LLC,B - Brick/Stone,553.0,1970.0,W - Ht Water/Steam,...,N - None,STRATHMORE RD,NaN,NaN,"$4,119.11",NaN,"377,900",22c@62j-sgc-7dv,22c@62j-sgc-7dv,22c@62j-sgc-7dv
2102732000,2.102732e+09,1,42.343485,NaN,2.0,YEE XIAO WEI SITU,B - Brick/Stone,1020.0,1970.0,W - Ht Water/Steam,...,N - None,Colborne RD,NaN,25025.0,"$5,221.10",NaN,"479,000",229@62j-sgj-ysq,229@62j-sgj-ysq,229@62j-sgj-ysq
2102770000,2.102770e+09,1,42.344492,NaN,2.0,TORAH ACADEMY INC,W - Wood Shake,1575.0,2021.0,W - Ht Water/Steam,...,N - None,Priscilla RD,NaN,25025.0,"$6,332.90",S - Semi-Modern,"581,000",228@62j-sgj-vfz,228@62j-sgj-vfz,228@62j-sgj-vfz
2200081000,NaN,1,42.359981,NaN,5.0,KOTOMORI EDWARD A,U - Alum Siding,4209.0,NaN,W - Ht Water/Steam,...,N - None,Windom ST,NaN,25025.0,"$9,547.31",S - Semi-Modern,"650,700",22c@62j-sjt-p9z,22c@62j-sjt-p9z,22c@62j-sjt-p9z
2200801000,2.200801e+09,1,42.361877,NaN,NaN,106-108 LITCHFIELD STREET,M - Vinyl,NaN,NaN,NaN,...,NaN,LITCHFIELD ST,2.0,25025.0,$-,NaN,0,23q@62j-sgk-j35,23q@62j-sgk-j35,23q@62j-sgk-j35

In [32]:
df.rename(columns={'OWNER':'Owned','St--Name':'Road Name'},inplace=True)

In [33]:
df.columns

Index(['Cm--Id', 'Bldg--Seq', 'Geocode--Latitude', 'Structure--Class',
       'Bed--Rms', 'Owned', 'Ext--Fnished', 'Gross--Area', 'Yr--Remodel',
       'Heat--Type', 'Full--Bth', 'Roof--Structure', 'Cd--Floor',
       'Mail--State', 'Kitchen--Style2', 'Sfyi--Value', 'Bthrm--Style3',
       'Int--Cond', 'Kitchen--Style3', 'Living--Area', 'City', 'Lu',
       'Int--Wall', 'Luc', 'Kitchen--Type', 'Overall--Cond', 'Land--Value',
       'Res--Floor', 'Bdrm--Cond', 'Roof--Cover', 'Pid', 'Kitchen--Style1',
       'Corner--Unit', 'Kitchens', 'Hlf--Bth', 'Fireplaces', 'Rc--Units',
       'Bldg--Type', 'Zip--Code', 'Land--Sf', 'Prop--View', 'Full--Address',
       'Geocode--Location--Type', 'Num--Bldgs', 'Mail--Addressee',
       'Mail--City', 'Yr--Built', 'Mail--Zip--Code', 'Lu--Desc', 'Parcel',
       'Com--Units', 'St--Num', 'Heat--System', 'Bthrm--Style1',
       'Confidence--Score', 'Tt--Rms', 'Own--Occ', 'Mail--Street--Address',
       'Upi', 'Ext--Cond', 'Unit--Num', 'Total--Value', 'Orientation',
       'Geocode--Longitude', 'Num--Parking', 'Ac--Type', 'Road Name',
       'Res--Units', 'Geoid', 'Gross--Tax', 'Bthrm--Style2', 'Bldg--Value',
       'Placekey', 'Address--Placekey', 'Building--Placekey'],
      dtype='str')